config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :tasks
  post 'tasks', to: 'tasks#create'
  get 'task/new', to: 'tasks#new', as: :task_new
  get 'tasks/:id', to: 'tasks#show', as: :task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :tasks_edit
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def new
    @task = Task.new
  end

  def show
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def edit
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTaskManager</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/a7d2aac0d7.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<% @tasks.each do |task| %>
<div class="title">
<!--   <h2><%= task.title %></h2> -->
  <%= form_for(task) do |f| %>
  <%= f.check_box :completed, {}, true, false %>
  <%= link_to task.title, task_path(task) %>
  <% end %>
</div>
<% end %>
<br>
<br>
<div>
  <%= link_to task_new_path do %>
    <i class="fas fa-plus"></i> Create new task
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= form_for(@task) do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :details %>
  <%= f.text_field :details, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.check_box :completed, {}, true, false %>
</div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>
<br>
<br>
<%= link_to "Back to task list", tasks_path %>

app/views/tasks/show.html.erb
  <h2><%= @task.title %></h2>
<div class="box">
  <p><%= @task.details %></p>
</div>
  <%= form_for(@task) do |f| %>
  <div class="title">
    <%= f.check_box :completed, {}, true, false %>
    <% if @task.completed %>
    <p>This task is completed.</p>
    <% else %>
    <p>This task is <strong>not</strong> completed.</p>
    <% end %>
  </div>
  <% end %>

<%= link_to "Back to task list", tasks_path %>